# Dataset paths and constants
COCO_LABELS = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
VOC_LABELS = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']
OPEN_IMAGES_LABELS = ['Accordion', 'Adhesive tape', 'Aircraft', 'Airplane', 'Alarm clock', 'Alpaca', 'Ambulance', 'Animal', 'Ant', 'Antelope', 'Apple', 'Armadillo', 'Artichoke', 'Auto part', 'Axe', 'Backpack', 'Bagel', 'Baked goods', 'Balance beam', 'Ball', 'Balloon', 'Banana', 'Band-aid', 'Banjo', 'Barge', 'Barrel', 'Baseball bat', 'Baseball glove', 'Bat (Animal)', 'Bathroom accessory', 'Bathroom cabinet', 'Bathtub', 'Beaker', 'Bear', 'Bed', 'Bee', 'Beehive', 'Beer', 'Beetle', 'Bell pepper', 'Belt', 'Bench', 'Bicycle', 'Bicycle helmet', 'Bicycle wheel', 'Bidet', 'Billboard', 'Billiard table', 'Binoculars', 'Bird', 'Blender', 'Blue jay', 'Boat', 'Bomb', 'Book', 'Bookcase', 'Boot', 'Bottle', 'Bottle opener', 'Bow and arrow', 'Bowl', 'Bowling equipment', 'Box', 'Boy', 'Brassiere', 'Bread', 'Briefcase', 'Broccoli', 'Bronze sculpture', 'Brown bear', 'Building', 'Bull', 'Burrito', 'Bus', 'Bust', 'Butterfly', 'Cabbage', 'Cabinetry', 'Cake', 'Cake stand', 'Calculator', 'Camel', 'Camera', 'Can opener', 'Canary', 'Candle', 'Candy', 'Cannon', 'Canoe', 'Cantaloupe', 'Car', 'Carnivore', 'Carrot', 'Cart', 'Cassette deck', 'Castle', 'Cat', 'Cat furniture', 'Caterpillar', 'Cattle', 'Ceiling fan', 'Cello', 'Centipede', 'Chainsaw', 'Chair', 'Cheese', 'Cheetah', 'Chest of drawers', 'Chicken', 'Chime', 'Chisel', 'Chopsticks', 'Christmas tree', 'Clock', 'Closet', 'Clothing', 'Coat', 'Cocktail', 'Cocktail shaker', 'Coconut', 'Coffee', 'Coffee cup', 'Coffee table', 'Coffeemaker', 'Coin', 'Common fig', 'Common sunflower', 'Computer keyboard', 'Computer monitor', 'Computer mouse', 'Container', 'Convenience store', 'Cookie', 'Cooking spray', 'Corded phone', 'Cosmetics', 'Couch', 'Countertop', 'Cowboy hat', 'Crab', 'Cream', 'Cricket ball', 'Crocodile', 'Croissant', 'Crown', 'Crutch', 'Cucumber', 'Cupboard', 'Curtain', 'Cutting board', 'Dagger', 'Dairy Product', 'Deer', 'Desk', 'Dessert', 'Diaper', 'Dice', 'Digital clock', 'Dinosaur', 'Dishwasher', 'Dog', 'Dog bed', 'Doll', 'Dolphin', 'Door', 'Door handle', 'Doughnut', 'Dragonfly', 'Drawer', 'Dress', 'Drill (Tool)', 'Drink', 'Drinking straw', 'Drum', 'Duck', 'Dumbbell', 'Eagle', 'Earrings', 'Egg (Food)', 'Elephant', 'Envelope', 'Eraser', 'Face powder', 'Facial tissue holder', 'Falcon', 'Fashion accessory', 'Fast food', 'Fax', 'Fedora', 'Filing cabinet', 'Fire hydrant', 'Fireplace', 'Fish', 'Flag', 'Flashlight', 'Flower', 'Flowerpot', 'Flute', 'Flying disc', 'Food', 'Food processor', 'Football', 'Football helmet', 'Footwear', 'Fork', 'Fountain', 'Fox', 'French fries', 'French horn', 'Frog', 'Fruit', 'Frying pan', 'Furniture', 'Garden Asparagus', 'Gas stove', 'Giraffe', 'Girl', 'Glasses', 'Glove', 'Goat', 'Goggles', 'Goldfish', 'Golf ball', 'Golf cart', 'Gondola', 'Goose', 'Grape', 'Grapefruit', 'Grinder', 'Guacamole', 'Guitar', 'Hair dryer', 'Hair spray', 'Hamburger', 'Hammer', 'Hamster', 'Hand dryer', 'Handbag', 'Handgun', 'Harbor seal', 'Harmonica', 'Harp', 'Harpsichord', 'Hat', 'Headphones', 'Heater', 'Hedgehog', 'Helicopter', 'Helmet', 'High heels', 'Hiking equipment', 'Hippopotamus', 'Home appliance', 'Honeycomb', 'Horizontal bar', 'Horse', 'Hot dog', 'House', 'Houseplant', 'Human arm', 'Human beard', 'Human body', 'Human ear', 'Human eye', 'Human face', 'Human foot', 'Human hair', 'Human hand', 'Human head', 'Human leg', 'Human mouth', 'Human nose', 'Humidifier', 'Ice cream', 'Indoor rower', 'Infant bed', 'Insect', 'Invertebrate', 'Ipod', 'Isopod', 'Jacket', 'Jacuzzi', 'Jaguar (Animal)', 'Jeans', 'Jellyfish', 'Jet ski', 'Jug', 'Juice', 'Kangaroo', 'Kettle', 'Kitchen & dining room table', 'Kitchen appliance', 'Kitchen knife', 'Kitchen utensil', 'Kitchenware', 'Kite', 'Knife', 'Koala', 'Ladder', 'Ladle', 'Ladybug', 'Lamp', 'Land vehicle', 'Lantern', 'Laptop', 'Lavender (Plant)', 'Lemon', 'Leopard', 'Light bulb', 'Light switch', 'Lighthouse', 'Lily', 'Limousine', 'Lion', 'Lipstick', 'Lizard', 'Lobster', 'Loveseat', 'Luggage and bags', 'Lynx', 'Magpie', 'Mammal', 'Man', 'Mango', 'Maple', 'Maracas', 'Marine invertebrates', 'Marine mammal', 'Measuring cup', 'Mechanical fan', 'Medical equipment', 'Microphone', 'Microwave oven', 'Milk', 'Miniskirt', 'Mirror', 'Missile', 'Mixer', 'Mixing bowl', 'Mobile phone', 'Monkey', 'Moths and butterflies', 'Motorcycle', 'Mouse', 'Muffin', 'Mug', 'Mule', 'Mushroom', 'Musical instrument', 'Musical keyboard', 'Nail (Construction)', 'Necklace', 'Nightstand', 'Oboe', 'Office building', 'Office supplies', 'Orange', 'Organ (Musical Instrument)', 'Ostrich', 'Otter', 'Oven', 'Owl', 'Oyster', 'Paddle', 'Palm tree', 'Pancake', 'Panda', 'Paper cutter', 'Paper towel', 'Parachute', 'Parking meter', 'Parrot', 'Pasta', 'Pastry', 'Peach', 'Pear', 'Pen', 'Pencil case', 'Pencil sharpener', 'Penguin', 'Perfume', 'Person', 'Personal care', 'Personal flotation device', 'Piano', 'Picnic basket', 'Picture frame', 'Pig', 'Pillow', 'Pineapple', 'Pitcher (Container)', 'Pizza', 'Pizza cutter', 'Plant', 'Plastic bag', 'Plate', 'Platter', 'Plumbing fixture', 'Polar bear', 'Pomegranate', 'Popcorn', 'Porch', 'Porcupine', 'Poster', 'Potato', 'Power plugs and sockets', 'Pressure cooker', 'Pretzel', 'Printer', 'Pumpkin', 'Punching bag', 'Rabbit', 'Raccoon', 'Racket', 'Radish', 'Ratchet (Device)', 'Raven', 'Rays and skates', 'Red panda', 'Refrigerator', 'Remote control', 'Reptile', 'Rhinoceros', 'Rifle', 'Ring binder', 'Rocket', 'Roller skates', 'Rose', 'Rugby ball', 'Ruler', 'Salad', 'Salt and pepper shakers', 'Sandal', 'Sandwich', 'Saucer', 'Saxophone', 'Scale', 'Scarf', 'Scissors', 'Scoreboard', 'Scorpion', 'Screwdriver', 'Sculpture', 'Sea lion', 'Sea turtle', 'Seafood', 'Seahorse', 'Seat belt', 'Segway', 'Serving tray', 'Sewing machine', 'Shark', 'Sheep', 'Shelf', 'Shellfish', 'Shirt', 'Shorts', 'Shotgun', 'Shower', 'Shrimp', 'Sink', 'Skateboard', 'Ski', 'Skirt', 'Skull', 'Skunk', 'Skyscraper', 'Slow cooker', 'Snack', 'Snail', 'Snake', 'Snowboard', 'Snowman', 'Snowmobile', 'Snowplow', 'Soap dispenser', 'Sock', 'Sofa bed', 'Sombrero', 'Sparrow', 'Spatula', 'Spice rack', 'Spider', 'Spoon', 'Sports equipment', 'Sports uniform', 'Squash (Plant)', 'Squid', 'Squirrel', 'Stairs', 'Stapler', 'Starfish', 'Stationary bicycle', 'Stethoscope', 'Stool', 'Stop sign', 'Strawberry', 'Street light', 'Stretcher', 'Studio couch', 'Submarine', 'Submarine sandwich', 'Suit', 'Suitcase', 'Sun hat', 'Sunglasses', 'Surfboard', 'Sushi', 'Swan', 'Swim cap', 'Swimming pool', 'Swimwear', 'Sword', 'Syringe', 'Table', 'Table tennis racket', 'Tablet computer', 'Tableware', 'Taco', 'Tank', 'Tap', 'Tart', 'Taxi', 'Tea', 'Teapot', 'Teddy bear', 'Telephone', 'Television', 'Tennis ball', 'Tennis racket', 'Tent', 'Tiara', 'Tick', 'Tie', 'Tiger', 'Tin can', 'Tire', 'Toaster', 'Toilet', 'Toilet paper', 'Tomato', 'Tool', 'Toothbrush', 'Torch', 'Tortoise', 'Towel', 'Tower', 'Toy', 'Traffic light', 'Traffic sign', 'Train', 'Training bench', 'Treadmill', 'Tree', 'Tree house', 'Tripod', 'Trombone', 'Trousers', 'Truck', 'Trumpet', 'Turkey', 'Turtle', 'Umbrella', 'Unicycle', 'Van', 'Vase', 'Vegetable', 'Vehicle', 'Vehicle registration plate', 'Violin', 'Volleyball (Ball)', 'Waffle', 'Waffle iron', 'Wall clock', 'Wardrobe', 'Washing machine', 'Waste container', 'Watch', 'Watercraft', 'Watermelon', 'Weapon', 'Whale', 'Wheel', 'Wheelchair', 'Whisk', 'Whiteboard', 'Willow', 'Window', 'Window blind', 'Wine', 'Wine glass', 'Wine rack', 'Winter melon', 'Wok', 'Woman', 'Wood-burning stove', 'Woodpecker', 'Worm', 'Wrench', 'Zebra', 'Zucchini']

# IoU threshold for matching two bboxes
IOU_THRESHOLD = 0.5

# Minimum size of the bounding box to be considered
MIN_BBOX_SIZE = 4000

# Constants for cloud correction
CROP_PADDING = 50  # Padding for cropping around in bbox from the original image
ACCEPTANCE_MARGIN = 40 # Margin for accepting a prediction from the cloud

# Constants for packing crops
PACKING_PADDING = 35
GRID_WIDTH, GRID_HEIGHT = 2, 2

# Whether to remove labels from the edge results if the cloud prediction does not include them
REMOVE_LABELS = False

OPEN_IMAGES_LABELS_MAP = {
    "Accordion": None,
    "Adhesive tape": None,
    "Aircraft": "Airplane",
    "Airplane": "Airplane",
    "Alarm clock": None,
    "Alpaca": None,
    "Ambulance": "Car",
    "Animal": None,
    "Ant": None,
    "Antelope": None,
    "Apple": "Apple",
    "Armadillo": None,
    "Artichoke": None,
    "Auto part": None,
    "Axe": None,
    "Backpack": "Bag",
    "Bagel": None,
    "Baked goods": None,
    "Balance beam": None,
    "Ball": None,
    "Balloon": None,
    "Banana": "Banana",
    "Band-aid": None,
    "Banjo": None,
    "Barge": None,
    "Barrel": None,
    "Baseball bat": None,
    "Baseball glove": None,
    "Bat (Animal)": "Bird",
    "Bathroom accessory": None,
    "Bathroom cabinet": None,
    "Bathtub": None,
    "Beaker": None,
    "Bear": None,
    "Bed": "Bed",
    "Bee": None,
    "Beehive": None,
    "Beer": None,
    "Beetle": None,
    "Bell pepper": None,
    "Belt": None,
    "Bench": None,
    "Bicycle": "Bicycle",
    "Bicycle helmet": "Helmet",
    "Bicycle wheel": "Wheel",
    "Bidet": None,
    "Billboard": None,
    "Billiard table": "Table",
    "Binoculars": None,
    "Bird": "Bird",
    "Blender": None,
    "Blue jay": None,
    "Boat": None,
    "Bomb": None,
    "Book": None,
    "Bookcase": None,
    "Boot": None,
    "Bottle": "Bottle",
    "Bottle opener": None,
    "Bow and arrow": None,
    "Bowl": None,
    "Bowling equipment": None,
    "Box": None,
    "Boy": "Person",
    "Brassiere": None,
    "Bread": None,
    "Briefcase": None,
    "Broccoli": None,
    "Bronze sculpture": None,
    "Brown bear": None,
    "Building": None,
    "Bull": None,
    "Burrito": None,
    "Bus": "Car",
    "Bust": None,
    "Butterfly": None,
    "Cabbage": None,
    "Cabinetry": None,
    "Cake": None,
    "Cake stand": None,
    "Calculator": None,
    "Camel": None,
    "Camera": None,
    "Can opener": None,
    "Canary": None,
    "Candle": None,
    "Candy": None,
    "Cannon": None,
    "Canoe": None,
    "Cantaloupe": None,
    "Car": "Car",
    "Carnivore": None,
    "Carrot": None,
    "Cart": None,
    "Cassette deck": None,
    "Castle": None,
    "Cat": None,
    "Cat furniture": None,
    "Caterpillar": None,
    "Cattle": None,
    "Ceiling fan": None,
    "Cello": None,
    "Centipede": None,
    "Chainsaw": None,
    "Chair": "Chair",
    "Cheese": None,
    "Cheetah": None,
    "Chest of drawers": None,
    "Chicken": "Bird",
    "Chime": None,
    "Chisel": None,
    "Chopsticks": None,
    "Christmas tree": None,
    "Clock": None,
    "Closet": None,
    "Clothing": None,
    "Coat": None,
    "Cocktail": None,
    "Cocktail shaker": None,
    "Coconut": None,
    "Coffee": None,
    "Coffee cup": "Cup",
    "Coffee table": "Table",
    "Coffeemaker": None,
    "Coin": None,
    "Common fig": None,
    "Common sunflower": None,
    "Computer keyboard": None,
    "Computer monitor": "TV",
    "Computer mouse": None,
    "Container": None,
    "Convenience store": None,
    "Cookie": None,
    "Cooking spray": None,
    "Corded phone": None,
    "Cosmetics": None,
    "Couch": None,
    "Countertop": None,
    "Cowboy hat": None,
    "Crab": None,
    "Cream": None,
    "Cricket ball": None,
    "Crocodile": None,
    "Croissant": None,
    "Crown": None,
    "Crutch": None,
    "Cucumber": None,
    "Cupboard": None,
    "Curtain": None,
    "Cutting board": None,
    "Dagger": None,
    "Dairy Product": None,
    "Deer": None,
    "Desk": None,
    "Dessert": None,
    "Diaper": None,
    "Dice": None,
    "Digital clock": None,
    "Dinosaur": None,
    "Dishwasher": None,
    "Dog": None,
    "Dog bed": None,
    "Doll": None,
    "Dolphin": None,
    "Door": None,
    "Door handle": None,
    "Doughnut": None,
    "Dragonfly": None,
    "Drawer": None,
    "Dress": None,
    "Drill (Tool)": None,
    "Drink": None,
    "Drinking straw": None,
    "Drum": None,
    "Duck": "Bird",
    "Dumbbell": None,
    "Eagle": "Bird",
    "Earrings": None,
    "Egg (Food)": None,
    "Elephant": None,
    "Envelope": None,
    "Eraser": None,
    "Face powder": None,
    "Facial tissue holder": None,
    "Falcon": None,
    "Fashion accessory": None,
    "Fast food": None,
    "Fax": None,
    "Fedora": None,
    "Filing cabinet": None,
    "Fire hydrant": None,
    "Fireplace": None,
    "Fish": None,
    "Flag": None,
    "Flashlight": None,
    "Flower": "Flower",
    "Flowerpot": None,
    "Flute": None,
    "Flying disc": None,
    "Food": None,
    "Food processor": None,
    "Football": "Ball",
    "Football helmet": "Helmet",
    "Footwear": None,
    "Fork": None,
    "Fountain": None,
    "Fox": None,
    "French fries": None,
    "French horn": None,
    "Frog": None,
    "Fruit": None,
    "Frying pan": None,
    "Furniture": None,
    "Garden Asparagus": None,
    "Gas stove": None,
    "Giraffe": None,
    "Girl": "Person",
    "Glasses": None,
    "Glove": None,
    "Goat": None,
    "Goggles": None,
    "Goldfish": None,
    "Golf ball": None,
    "Golf cart": "Car",
    "Gondola": None,
    "Goose": None,
    "Grape": None,
    "Grapefruit": None,
    "Grinder": None,
    "Guacamole": None,
    "Guitar": None,
    "Hair dryer": None,
    "Hair spray": None,
    "Hamburger": None,
    "Hammer": None,
    "Hamster": None,
    "Hand dryer": None,
    "Handbag": "Bag",
    "Handgun": None,
    "Harbor seal": None,
    "Harmonica": None,
    "Harp": None,
    "Harpsichord": None,
    "Hat": None,
    "Headphones": None,
    "Heater": None,
    "Hedgehog": None,
    "Helicopter": None,
    "Helmet": "Helmet",
    "High heels": None,
    "Hiking equipment": None,
    "Hippopotamus": None,
    "Home appliance": None,
    "Honeycomb": None,
    "Horizontal bar": None,
    "Horse": None,
    "Hot dog": None,
    "House": None,
    "Houseplant": None,
    "Human arm": None,
    "Human beard": None,
    "Human body": None,
    "Human ear": None,
    "Human eye": None,
    "Human face": None,
    "Human foot": None,
    "Human hair": None,
    "Human hand": None,
    "Human head": None,
    "Human leg": None,
    "Human mouth": None,
    "Human nose": None,
    "Humidifier": None,
    "Ice cream": None,
    "Indoor rower": None,
    "Infant bed": None,
    "Insect": None,
    "Invertebrate": None,
    "Ipod": None,
    "Isopod": None,
    "Jacket": None,
    "Jacuzzi": None,
    "Jaguar (Animal)": None,
    "Jeans": None,
    "Jellyfish": None,
    "Jet ski": None,
    "Jug": None,
    "Juice": None,
    "Kangaroo": None,
    "Kettle": None,
    "Kitchen & dining room table": "Table",
    "Kitchen appliance": None,
    "Kitchen knife": None,
    "Kitchen utensil": None,
    "Kitchenware": None,
    "Kite": None,
    "Knife": None,
    "Koala": None,
    "Ladder": None,
    "Ladle": None,
    "Ladybug": None,
    "Lamp": None,
    "Land vehicle": None,
    "Lantern": None,
    "Laptop": "Laptop",
    "Lavender (Plant)": None,
    "Lemon": None,
    "Leopard": None,
    "Light bulb": None,
    "Light switch": None,
    "Lighthouse": None,
    "Lily": None,
    "Limousine": None,
    "Lion": None,
    "Lipstick": None,
    "Lizard": None,
    "Lobster": None,
    "Loveseat": None,
    "Luggage and bags": "Bag",
    "Lynx": None,
    "Magpie": None,
    "Mammal": None,
    "Man": "Person",
    "Mango": None,
    "Maple": None,
    "Maracas": None,
    "Marine invertebrates": None,
    "Marine mammal": None,
    "Measuring cup": None,
    "Mechanical fan": None,
    "Medical equipment": None,
    "Microphone": None,
    "Microwave oven": None,
    "Milk": None,
    "Miniskirt": None,
    "Mirror": None,
    "Missile": None,
    "Mixer": None,
    "Mixing bowl": None,
    "Mobile phone": None,
    "Monkey": None,
    "Moths and butterflies": None,
    "Motorcycle": "Motorcycle",
    "Mouse": None,
    "Muffin": None,
    "Mug": "Cup",
    "Mule": None,
    "Mushroom": None,
    "Musical instrument": None,
    "Musical keyboard": None,
    "Nail (Construction)": None,
    "Necklace": None,
    "Nightstand": None,
    "Oboe": None,
    "Office building": None,
    "Office supplies": None,
    "Orange": None,
    "Organ (Musical Instrument)": None,
    "Ostrich": None,
    "Otter": None,
    "Oven": None,
    "Owl": "Bird",
    "Oyster": None,
    "Paddle": None,
    "Palm tree": None,
    "Pancake": None,
    "Panda": None,
    "Paper cutter": None,
    "Paper towel": None,
    "Parachute": None,
    "Parking meter": None,
    "Parrot": "Bird",
    "Pasta": None,
    "Pastry": None,
    "Peach": None,
    "Pear": None,
    "Pen": None,
    "Pencil case": None,
    "Pencil sharpener": None,
    "Penguin": "Bird",
    "Perfume": None,
    "Person": "Person",
    "Personal care": None,
    "Personal flotation device": None,
    "Piano": None,
    "Picnic basket": None,
    "Picture frame": None,
    "Pig": None,
    "Pillow": None,
    "Pineapple": None,
    "Pitcher (Container)": None,
    "Pizza": None,
    "Pizza cutter": None,
    "Plant": None,
    "Plastic bag": None,
    "Plate": None,
    "Platter": None,
    "Plumbing fixture": None,
    "Polar bear": None,
    "Pomegranate": None,
    "Popcorn": None,
    "Porch": None,
    "Porcupine": None,
    "Poster": None,
    "Potato": None,
    "Power plugs and sockets": None,
    "Pressure cooker": None,
    "Pretzel": None,
    "Printer": None,
    "Pumpkin": None,
    "Punching bag": None,
    "Rabbit": None,
    "Raccoon": None,
    "Racket": None,
    "Radish": None,
    "Ratchet (Device)": None,
    "Raven": None,
    "Rays and skates": None,
    "Red panda": None,
    "Refrigerator": None,
    "Remote control": None,
    "Reptile": None,
    "Rhinoceros": None,
    "Rifle": None,
    "Ring binder": None,
    "Rocket": None,
    "Roller skates": None,
    "Rose": None,
    "Rugby ball": None,
    "Ruler": None,
    "Salad": None,
    "Salt and pepper shakers": None,
    "Sandal": None,
    "Sandwich": None,
    "Saucer": None,
    "Saxophone": None,
    "Scale": None,
    "Scarf": None,
    "Scissors": None,
    "Scoreboard": None,
    "Scorpion": None,
    "Screwdriver": None,
    "Sculpture": None,
    "Sea lion": None,
    "Sea turtle": None,
    "Seafood": None,
    "Seahorse": None,
    "Seat belt": None,
    "Segway": None,
    "Serving tray": None,
    "Sewing machine": None,
    "Shark": None,
    "Sheep": None,
    "Shelf": None,
    "Shellfish": None,
    "Shirt": None,
    "Shorts": None,
    "Shotgun": None,
    "Shower": None,
    "Shrimp": None,
    "Sink": None,
    "Skateboard": None,
    "Ski": None,
    "Skirt": None,
    "Skull": None,
    "Skunk": None,
    "Skyscraper": None,
    "Slow cooker": None,
    "Snack": None,
    "Snail": None,
    "Snake": None,
    "Snowboard": None,
    "Snowman": None,
    "Snowmobile": None,
    "Snowplow": None,
    "Soap dispenser": None,
    "Sock": None,
    "Sofa bed": "Bed",
    "Sombrero": None,
    "Sparrow": None,
    "Spatula": None,
    "Spice rack": None,
    "Spider": None,
    "Spoon": None,
    "Sports equipment": None,
    "Sports uniform": None,
    "Squash (Plant)": None,
    "Squid": None,
    "Squirrel": None,
    "Stairs": None,
    "Stapler": None,
    "Starfish": None,
    "Stationary bicycle": "Bicycle",
    "Stethoscope": None,
    "Stool": "Chair",
    "Stop sign": None,
    "Strawberry": None,
    "Street light": None,
    "Stretcher": None,
    "Studio couch": None,
    "Submarine": None,
    "Submarine sandwich": None,
    "Suit": None,
    "Suitcase": "Bag",
    "Sun hat": None,
    "Sunglasses": None,
    "Surfboard": None,
    "Sushi": None,
    "Swan": "Bird",
    "Swim cap": None,
    "Swimming pool": None,
    "Swimwear": None,
    "Sword": None,
    "Syringe": None,
    "Table": "Table",
    "Table tennis racket": None,
    "Tablet computer": None,
    "Tableware": None,
    "Taco": None,
    "Tank": None,
    "Tap": None,
    "Tart": None,
    "Taxi": None,
    "Tea": None,
    "Teapot": None,
    "Teddy bear": None,
    "Telephone": None,
    "Television": "TV",
    "Tennis ball": None,
    "Tennis racket": None,
    "Tent": None,
    "Tiara": None,
    "Tick": None,
    "Tie": None,
    "Tiger": None,
    "Tin can": None,
    "Tire": None,
    "Toaster": None,
    "Toilet": None,
    "Toilet paper": None,
    "Tomato": None,
    "Tool": None,
    "Toothbrush": None,
    "Torch": None,
    "Tortoise": None,
    "Towel": None,
    "Tower": None,
    "Toy": None,
    "Traffic light": None,
    "Traffic sign": None,
    "Train": None,
    "Training bench": None,
    "Treadmill": None,
    "Tree": None,
    "Tree house": None,
    "Tripod": None,
    "Trombone": None,
    "Trousers": None,
    "Truck": "Car",
    "Trumpet": None,
    "Turkey": None,
    "Turtle": None,
    "Umbrella": None,
    "Unicycle": None,
    "Van": "Car",
    "Vase": None,
    "Vegetable": None,
    "Vehicle": "Car",
    "Vehicle registration plate": None,
    "Violin": None,
    "Volleyball (Ball)": "Ball",
    "Waffle": None,
    "Waffle iron": None,
    "Wall clock": None,
    "Wardrobe": None,
    "Washing machine": None,
    "Waste container": None,
    "Watch": None,
    "Watercraft": None,
    "Watermelon": None,
    "Weapon": None,
    "Whale": None,
    "Wheel": "Wheel",
    "Wheelchair": None,
    "Whisk": None,
    "Whiteboard": None,
    "Willow": None,
    "Window": None,
    "Window blind": None,
    "Wine": None,
    "Wine glass": None,
    "Wine rack": None,
    "Winter melon": None,
    "Wok": None,
    "Woman": "Person",
    "Wood-burning stove": None,
    "Woodpecker": None,
    "Worm": None,
    "Wrench": None,
    "Zebra": None,
    "Zucchini": None,
}